name: $(BuildDefinitionName)-$(Date:yyyyMMdd).$(Rev:.r)

trigger:
- master

pool:
 # vmImage: 'vs2017-win2016'
  name: Default

steps:
- powershell: $BuildSourceDirectory\BuildAutomation\BuildAutomation\DeployPackage.ps1
   
  displayName: 'Deploying CRM package by using defined varibles'
